### ISSUE TITLE
[bug] Validation failed for field `output` in class fast_llm.tools.convert.ConversionConfig

### ISSUE THREAD

**Issue by sohamparikh** [ServiceNow/Fast-LLM#79]
# 🐞 Describe the Bug

Running the conversion script throws an error in `fast_llm/engine/checkpoint/config.py`: `AttributeError: 'str' object has no attribute 'support_optimizer'`

# 🔄 Steps to Reproduce

1. Docker image tag: `sha-49acd10`
2. Run the following command

    ```bash
    fast-llm convert gpt \
      input.path=<input_path> \
      output.path=<output_path> \
      input.format=fast_llm \
      output.format=auto \
      use_cpu=False \
      exist_ok=True \
      layers_per_step=1
    ```
Tried with both input formats `fast_llm` and `gpt`

3. YAML Configuration:
```
--------- fast_llm.tools.convert.ConversionConfig ----------
input:
  format: fast_llm
  path: <input_path>
  load_config: architecture
output:
  format: auto
  path: <output_path>
exist_ok: true
layers_per_step: 1
--------------------------- end ----------------------------
```
4. Error Seen:

```
2024-12-02 18:58:29,105 Traceback (most recent call last):
  File "/app/fast_llm/tools/cli.py", line 29, in fast_llm
    Runnable.parse_and_run(unparsed)
  File "/app/fast_llm/engine/config_utils/runnable.py", line 28, in parse_and_run
    config.validate()
  File "/app/fast_llm/config.py", line 333, in validate
    raise type(e)("\n".join(e.args)) from None
fast_llm.config.NestedValidationError: Validation failed for field `input` of type `fast_llm.engine.checkpoint.config.CheckpointLoadConfig` in class fast_llm.tools.convert.ConversionConfig:
  Validation failed for field `format` of type `type` in class fast_llm.engine.checkpoint.config.CheckpointLoadConfig: Unexpected type `str`
Validation failed for field `output` in class fast_llm.tools.convert.ConversionConfig: 'str' object has no attribute 'support_optimizer'
====================== stack trace ========================
Traceback (most recent call last):
  File "/app/fast_llm/config.py", line 362, in _validate_nested
    value = cls._validate_element(value, type_, name)
  File "/app/fast_llm/config.py", line 417, in _validate_element
    value.validate(_is_validating=True)
  File "/app/fast_llm/config.py", line 328, in validate
    self._validate()
  File "/app/fast_llm/engine/checkpoint/config.py", line 179, in _validate
    self.optimizer_state = self.format.support_optimizer
AttributeError: 'str' object has no attribute 'support_optimizer'
===========================================================
```

# 🎯 Expected Behavior

Should not throw an error

**Comment by RaymondLi0** [comment]
I think it might be due to #31 . The change https://github.com/ServiceNow/Fast-LLM/pull/31/files#diff-7918450e1f40c08873e1cbe114c93949a569d4a5ebea4d3651076f238961e667R117 broke the way config is loaded in `convert.py`

**Comment by RaymondLi0** [comment]
In the meantime, you could also test conversion by running the test: https://github.com/ServiceNow/Fast-LLM/blob/main/tests/test_checkpoint.py

**Comment by jlamypoirier** [comment]
Looks like a missing config setup that converts str to type, should be an easy fix
